/**
 * Component ID generation for pages.json nodes.
 *
 * IDs are always auto-generated by tooling — never specified by users or AI.
 * Format: {type}-{5 random chars}, e.g. "btn-a7x3k", "table-k8m2p"
 */

import { nanoid } from 'nanoid';

/**
 * Generate a stable component ID for the given component type.
 * Uses a 5-char random suffix which gives ~1B combinations per type.
 */
export function generateNodeId(type: string): string {
  // Sanitize type to be URL/CSS-safe (replace non-alphanumeric except hyphen)
  const safeType = type.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
  return `${safeType}-${nanoid(5)}`;
}
