/**
 * Page Editor — Core logic for structured editing of ui/pages.json
 *
 * Provides read and write operations for pages.json in the Agent working copy.
 * All write operations:
 *   1. Normalize (auto-assign missing IDs)
 *   2. Validate (Zod structure + semantic checks)
 *   3. Write back to working copy only if validation passes
 *
 * IDs are auto-generated by this module; callers must not specify IDs.
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

import {
  normalizePagesJson,
  validatePagesJson,
  generateNodeId,
  getComponentSummary,
  isContainerType,
} from '@cozybase/ui';
import type { PagesJson, ComponentSchema } from '@cozybase/ui';

const PAGES_JSON_PATH = 'ui/pages.json';

// ============================================================
// Types
// ============================================================

export interface PageEditorContext {
  appsDir: string;
  appName: string;
}

export interface OutlineNode {
  id: string;
  type: string;
  summary: string;
  children?: OutlineNode[];
}

export interface PageOutline {
  id: string;
  title: string;
  body: OutlineNode[];
}

export interface PageOutlineResult {
  pages: PageOutline[];
}

export interface PageSummary {
  id: string;
  title: string;
}

export interface PagesListResult {
  pages: PageSummary[];
}

export type BatchOperation =
  | {
    op: 'get';
    ref?: string;
    node_id: string;
  }
  | {
    op: 'insert';
    ref?: string;
    parent_id: string;
    node: Record<string, unknown>;
    index?: number;
  }
  | {
    op: 'update';
    ref?: string;
    node_id: string;
    props: Record<string, unknown>;
  }
  | {
    op: 'delete';
    ref?: string;
    node_id: string;
  }
  | {
    op: 'move';
    ref?: string;
    node_id: string;
    new_parent_id: string;
    index?: number;
  }
  | {
    op: 'page_add';
    ref?: string;
    id: string;
    title: string;
    index?: number;
  }
  | {
    op: 'page_remove';
    ref?: string;
    page_id: string;
  }
  | {
    op: 'page_update';
    ref?: string;
    page_id: string;
    title: string;
  };

export interface BatchError {
  code: string;
  message: string;
  details?: unknown;
}

export interface BatchOperationResult {
  index: number;
  op: BatchOperation['op'];
  status: 'ok' | 'error' | 'skipped';
  ref?: string;
  node_id?: string;
  page_id?: string;
  node?: ComponentSchema;
  page?: PageSummary;
  deleted?: string;
  skipped_reason?: string;
  error?: BatchError;
}

export interface BatchResult {
  committed: boolean;
  results: BatchOperationResult[];
  write_error?: BatchError;
}

export class PageEditorError extends Error {
  constructor(
    message: string,
    public readonly code:
      | 'FILE_NOT_FOUND'
      | 'INVALID_JSON'
      | 'VALIDATION_ERROR'
      | 'NODE_NOT_FOUND'
      | 'INVALID_PARENT'
      | 'FORBIDDEN_UPDATE',
    public readonly details?: unknown,
  ) {
    super(message);
    this.name = 'PageEditorError';
  }
}

// ============================================================
// File I/O
// ============================================================

function getPagesJsonPath(ctx: PageEditorContext): string {
  return join(ctx.appsDir, ctx.appName, PAGES_JSON_PATH);
}

function readPagesJson(ctx: PageEditorContext): PagesJson {
  const filePath = getPagesJsonPath(ctx);
  if (!existsSync(filePath)) {
    throw new PageEditorError(
      `pages.json not found for app "${ctx.appName}". Run fetch_app first.`,
      'FILE_NOT_FOUND',
    );
  }

  let raw: unknown;
  let rawText: string;
  try {
    rawText = readFileSync(filePath, 'utf-8');
    raw = JSON.parse(rawText);
  } catch (e) {
    throw new PageEditorError(
      `Failed to parse pages.json: ${e instanceof Error ? e.message : String(e)}`,
      'INVALID_JSON',
    );
  }

  // Normalize (auto-assign IDs to any nodes missing them, mutates in place)
  normalizePagesJson(raw);

  // Validate after normalization
  const result = validatePagesJson(raw);
  if (!result.ok) {
    throw new PageEditorError(
      'pages.json has validation errors:\n' +
        result.errors.map((e) => `  ${e.path}: ${e.message}`).join('\n'),
      'VALIDATION_ERROR',
      result.errors,
    );
  }

  // Persist normalized IDs back to disk so repeated reads are stable.
  // Only write if normalization actually changed something.
  const normalizedText = JSON.stringify(result.data, null, 2);
  if (normalizedText !== rawText.trimEnd()) {
    writeFileSync(filePath, normalizedText, 'utf-8');
  }

  return result.data;
}

function writePagesJson(ctx: PageEditorContext, data: unknown): PagesJson {
  // Normalize before validating
  normalizePagesJson(data);

  // Validate
  const result = validatePagesJson(data);
  if (!result.ok) {
    throw new PageEditorError(
      'Validation failed — changes were not written:\n' +
        result.errors.map((e) => `  ${e.path}: ${e.message}`).join('\n'),
      'VALIDATION_ERROR',
      result.errors,
    );
  }

  // Write to working copy
  const filePath = getPagesJsonPath(ctx);
  writeFileSync(filePath, JSON.stringify(result.data, null, 2), 'utf-8');
  return result.data;
}

// ============================================================
// Shared component-slot walker
// ============================================================

/**
 * A visitor callback receives the child node, the mutable array it lives in,
 * its index within that array, and an optional SlotMutator for singleton slots.
 *
 * For normal array slots (children[], body[], etc.), `siblings` is the actual
 * array in the parent object, so `siblings[index] = x` and `siblings.splice()`
 * persist correctly.
 *
 * For singleton slots (itemRender, columns[].render, dialog-action body),
 * `slotMutator` is provided:
 *   - `slotMutator.set(node)` replaces the singleton in the parent object.
 *   - `slotMutator.remove()` deletes it (only defined for optional slots like
 *     columns[].render — required slots like list.itemRender and dialog body
 *     do not provide `remove`).
 *   Do NOT mutate `siblings[index]` for singleton slots.
 */
interface SlotMutator {
  set: (newNode: ComponentSchema) => void;
  remove?: () => void;
}

type SlotVisitor = (
  child: ComponentSchema,
  siblings: ComponentSchema[],
  index: number,
  slotMutator?: SlotMutator,
) => void;

/**
 * Visit every direct component child of `node` across ALL component-bearing
 * slots defined in the schema:
 *
 *   children[]        – row, col, card, dialog
 *   body[]            – card (alternate layout), tabs items, custom components
 *   items[i].body[]   – tabs panel bodies
 *   itemRender        – list (singleton)
 *   columns[i].render – table (singleton per column)
 *   action/onSuccess/onError body  – dialog-type actions (singleton)
 *
 * This is the single source of truth for traversal — normalize, validate,
 * find, subtree-check, and outline all delegate here so they stay in sync.
 */
function visitChildComponents(node: ComponentSchema, visitor: SlotVisitor): void {
  const n = node as Record<string, unknown>;

  // Standard array slots
  if (Array.isArray(n.children)) {
    const arr = n.children as ComponentSchema[];
    for (let i = 0; i < arr.length; i++) visitor(arr[i], arr, i);
  }

  if (Array.isArray(n.body)) {
    const arr = n.body as ComponentSchema[];
    for (let i = 0; i < arr.length; i++) visitor(arr[i], arr, i);
  }

  // tabs.items[].body
  if (Array.isArray(n.items)) {
    for (const tabItem of n.items as Array<Record<string, unknown>>) {
      if (Array.isArray(tabItem.body)) {
        const arr = tabItem.body as ComponentSchema[];
        for (let i = 0; i < arr.length; i++) visitor(arr[i], arr, i);
      }
    }
  }

  // list.itemRender (singleton, REQUIRED — no remove)
  if (n.itemRender && typeof n.itemRender === 'object' && !Array.isArray(n.itemRender)) {
    const wrapper = n.itemRender as ComponentSchema;
    visitor(wrapper, [wrapper], 0, {
      set: (newNode) => { n.itemRender = newNode; },
      // no remove: list.itemRender is required by schema
    });
  }

  // table.columns[].render (singleton per column, OPTIONAL — remove allowed)
  if (Array.isArray(n.columns)) {
    for (const col of n.columns as Array<Record<string, unknown>>) {
      if (col.render && typeof col.render === 'object') {
        const wrapper = col.render as ComponentSchema;
        visitor(wrapper, [wrapper], 0, {
          set: (newNode) => { col.render = newNode; },
          remove: () => { delete col.render; },
        });
      }
    }
  }

  // dialog-action bodies: action, onSuccess, onError (and nested confirm/cancel)
  visitActionComponentSlots(n.action, visitor);
  visitActionComponentSlots(n.onSuccess, visitor);
  visitActionComponentSlots(n.onError, visitor);

  if (Array.isArray(n.rowActions)) {
    for (const ra of n.rowActions as Array<Record<string, unknown>>) {
      visitActionComponentSlots(ra.action, visitor);
    }
  }
}

/** Recursively visit component-bearing slots inside action trees. */
function visitActionComponentSlots(actions: unknown, visitor: SlotVisitor): void {
  if (!actions) return;
  const list = Array.isArray(actions) ? actions : [actions];
  for (const action of list) {
    if (!action || typeof action !== 'object') continue;
    const a = action as Record<string, unknown>;
    if (a.type === 'dialog' && a.body && typeof a.body === 'object') {
      const wrapper = a.body as ComponentSchema;
      visitor(wrapper, [wrapper], 0, {
        set: (newNode) => { a.body = newNode; },
        // no remove: dialog action body is required by schema
      });
    }
    // Recurse into nested action chains
    visitActionComponentSlots(a.onSuccess, visitor);
    visitActionComponentSlots(a.onError, visitor);
    visitActionComponentSlots(a.onConfirm, visitor);
    visitActionComponentSlots(a.onCancel, visitor);
  }
}

// ============================================================
// Node traversal utilities
// ============================================================

interface NodeLocation {
  node: ComponentSchema;
  /** The array this node lives in */
  siblings: ComponentSchema[];
  /** Index within siblings */
  index: number;
  /**
   * For singleton slots, provides set/remove operations that persist to the
   * parent object. Undefined for normal array slots where direct array
   * mutation (`siblings[index] =`, `siblings.splice()`) works correctly.
   */
  slotMutator?: SlotMutator;
}

function findNodeById(
  data: PagesJson,
  nodeId: string,
): NodeLocation | null {
  for (const page of data.pages) {
    const found = findInArray(page.body, nodeId);
    if (found) return found;
  }
  return null;
}

function findInArray(
  arr: ComponentSchema[],
  nodeId: string,
): NodeLocation | null {
  for (let i = 0; i < arr.length; i++) {
    const node = arr[i];
    if ((node as { id: string }).id === nodeId) {
      return { node, siblings: arr, index: i };
    }
    const found = findInChildSlots(node, nodeId);
    if (found) return found;
  }
  return null;
}

function findInChildSlots(
  node: ComponentSchema,
  nodeId: string,
): NodeLocation | null {
  let result: NodeLocation | null = null;
  visitChildComponents(node, (child, siblings, index, slotMutator) => {
    if (result) return; // already found
    if ((child as { id: string }).id === nodeId) {
      result = { node: child, siblings, index, slotMutator };
      return;
    }
    const deeper = findInChildSlots(child, nodeId);
    if (deeper) result = deeper;
  });
  return result;
}

/**
 * Returns true if `targetId` appears anywhere in the subtree rooted at `node`
 * (including `node` itself). Used to prevent moving a node into its own subtree.
 */
function isAncestorOf(
  nodeToMove: ComponentSchema,
  targetId: string,
): boolean {
  if ((nodeToMove as { id: string }).id === targetId) return true;
  return subtreeContainsId(nodeToMove, targetId);
}

function subtreeContainsId(node: ComponentSchema, id: string): boolean {
  let found = false;
  visitChildComponents(node, (child) => {
    if (found) return;
    if ((child as { id: string }).id === id) {
      found = true;
      return;
    }
    if (subtreeContainsId(child, id)) found = true;
  });
  return found;
}

/** Get the mutable children array of a container node, if applicable. */
function getChildrenArray(node: ComponentSchema): ComponentSchema[] | null {
  const n = node as Record<string, unknown>;
  if (Array.isArray(n.children)) return n.children as ComponentSchema[];
  if (Array.isArray(n.body)) return n.body as ComponentSchema[];
  return null;
}

// ============================================================
// Outline generation
// ============================================================

function buildOutlineNode(node: ComponentSchema): OutlineNode {
  const n = node as Record<string, unknown>;
  const id = String(n.id ?? '');
  const type = String(n.type ?? '');
  const summary = getComponentSummary(n);

  // Collect all child outline nodes via the shared walker
  const childOutlines: OutlineNode[] = [];
  visitChildComponents(node, (child) => {
    childOutlines.push(buildOutlineNode(child));
  });

  if (childOutlines.length > 0) {
    return { id, type, summary, children: childOutlines };
  }
  return { id, type, summary };
}

// ============================================================
// In-memory operations
// ============================================================

/** Page id format: lowercase alphanumeric and hyphens, must start with a letter or digit. */
const PAGE_ID_PATTERN = /^[a-z0-9][a-z0-9-]*$/;
const NESTED_REF_TOKEN_PATTERN = /^\$[A-Za-z_][A-Za-z0-9_-]*$/;

function resolveNestedRefs<T>(
  value: T,
  refMap: ReadonlyMap<string, string>,
  path: string,
): T {
  if (typeof value === 'string') {
    if (!NESTED_REF_TOKEN_PATTERN.test(value)) {
      return value;
    }

    const resolved = refMap.get(value);
    if (resolved === undefined) {
      throw new PageEditorError(
        `Nested reference "${value}" at "${path}" is not defined in the current operation context.`,
        'VALIDATION_ERROR',
      );
    }
    return resolved as T;
  }

  if (Array.isArray(value)) {
    return value.map((item, index) => resolveNestedRefs(item, refMap, `${path}[${index}]`)) as T;
  }

  if (value && typeof value === 'object') {
    const result: Record<string, unknown> = {};
    for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
      result[key] = resolveNestedRefs(child, refMap, `${path}.${key}`);
    }
    return result as T;
  }

  return value;
}

function collectNestedRefTokens(value: unknown): string[] {
  if (typeof value === 'string') {
    return NESTED_REF_TOKEN_PATTERN.test(value) ? [value] : [];
  }

  if (Array.isArray(value)) {
    return value.flatMap((item) => collectNestedRefTokens(item));
  }

  if (value && typeof value === 'object') {
    return Object.values(value as Record<string, unknown>).flatMap((child) => collectNestedRefTokens(child));
  }

  return [];
}

function getNodeInMemory(data: PagesJson, nodeId: string): ComponentSchema {
  const location = findNodeById(data, nodeId);
  if (!location) {
    throw new PageEditorError(
      `Node with id "${nodeId}" not found in pages.json.`,
      'NODE_NOT_FOUND',
    );
  }
  return location.node;
}

function insertNodeInMemory(
  data: PagesJson,
  parentId: string,
  nodeData: Record<string, unknown>,
  index?: number,
  availableRefs: ReadonlyMap<string, string> = new Map(),
): { node: ComponentSchema; nodeId: string } {
  // Auto-generate ID — remove any id the caller may have specified
  const nodeType = String(nodeData.type ?? 'unknown');
  const newNodeId = generateNodeId(nodeType);
  const refContext = new Map(availableRefs);
  refContext.set('$self', newNodeId);
  const resolvedNodeData = resolveNestedRefs(nodeData, refContext, 'node');
  const newNode = {
    ...resolvedNodeData,
    id: newNodeId,
  } as ComponentSchema;

  // Check if parentId refers to a page (top-level body insertion)
  const page = data.pages.find((p) => p.id === parentId);
  if (page) {
    const body = page.body as ComponentSchema[];
    if (index !== undefined && index >= 0 && index <= body.length) {
      body.splice(index, 0, newNode);
    } else {
      body.push(newNode);
    }
    return { node: newNode, nodeId: newNodeId };
  }

  // Find parent component node
  const parentLocation = findNodeById(data, parentId);
  if (!parentLocation) {
    throw new PageEditorError(
      `Parent "${parentId}" not found in pages.json. Use a page id or a container node id.`,
      'INVALID_PARENT',
    );
  }

  const parentNode = parentLocation.node;

  // Check parent is a container type
  const parentType = (parentNode as { type: string }).type;
  if (!isContainerType(parentType)) {
    throw new PageEditorError(
      `Node "${parentId}" (type: "${parentType}") cannot contain children. Only container types can have children.`,
      'INVALID_PARENT',
    );
  }

  const children = getChildrenArray(parentNode);
  if (!children) {
    throw new PageEditorError(
      `Node "${parentId}" has no children array.`,
      'INVALID_PARENT',
    );
  }

  if (index !== undefined && index >= 0 && index <= children.length) {
    children.splice(index, 0, newNode);
  } else {
    children.push(newNode);
  }

  return { node: newNode, nodeId: newNodeId };
}

function assertNodeUpdatableProps(props: Record<string, unknown>): void {
  if ('id' in props) {
    throw new PageEditorError(
      'Cannot modify "id" via ui_update. Node IDs are stable and managed by the system.',
      'FORBIDDEN_UPDATE',
    );
  }
  if ('type' in props) {
    throw new PageEditorError(
      'Cannot modify "type" via ui_update. To change a node\'s type, use ui_delete then ui_insert.',
      'FORBIDDEN_UPDATE',
    );
  }
}

function updateNodeInMemory(
  data: PagesJson,
  nodeId: string,
  props: Record<string, unknown>,
): ComponentSchema {
  assertNodeUpdatableProps(props);

  const location = findNodeById(data, nodeId);
  if (!location) {
    throw new PageEditorError(
      `Node with id "${nodeId}" not found in pages.json.`,
      'NODE_NOT_FOUND',
    );
  }

  const updated = { ...(location.node as Record<string, unknown>), ...props } as ComponentSchema;
  if (location.slotMutator) {
    location.slotMutator.set(updated);
  } else {
    location.siblings[location.index] = updated;
  }

  return updated;
}

function moveNodeInMemory(
  data: PagesJson,
  nodeId: string,
  newParentId: string,
  index?: number,
): ComponentSchema {
  const nodeLocation = findNodeById(data, nodeId);
  if (!nodeLocation) {
    throw new PageEditorError(
      `Node with id "${nodeId}" not found in pages.json.`,
      'NODE_NOT_FOUND',
    );
  }

  // Guard: moving a node into its own subtree would corrupt the tree
  if (isAncestorOf(nodeLocation.node, newParentId)) {
    throw new PageEditorError(
      `Cannot move node "${nodeId}" into its own descendant "${newParentId}".`,
      'INVALID_PARENT',
    );
  }

  const parentLocation = findNodeById(data, newParentId);
  if (!parentLocation) {
    throw new PageEditorError(
      `Parent node "${newParentId}" not found in pages.json.`,
      'INVALID_PARENT',
    );
  }

  const parentType = (parentLocation.node as { type: string }).type;
  if (!isContainerType(parentType)) {
    throw new PageEditorError(
      `Node "${newParentId}" (type: "${parentType}") cannot contain children.`,
      'INVALID_PARENT',
    );
  }

  const targetChildren = getChildrenArray(parentLocation.node);
  if (!targetChildren) {
    throw new PageEditorError(
      `Parent node "${newParentId}" has no children array.`,
      'INVALID_PARENT',
    );
  }

  let removedNode: ComponentSchema;
  if (nodeLocation.slotMutator) {
    if (!nodeLocation.slotMutator.remove) {
      throw new PageEditorError(
        `Node "${nodeId}" is a required singleton slot (e.g. list.itemRender or dialog action body) ` +
        'and cannot be moved out of its parent. Delete the parent node and re-insert instead.',
        'INVALID_PARENT',
      );
    }
    removedNode = nodeLocation.node;
    nodeLocation.slotMutator.remove();
  } else {
    [removedNode] = nodeLocation.siblings.splice(nodeLocation.index, 1);
  }

  if (index !== undefined && index >= 0 && index <= targetChildren.length) {
    targetChildren.splice(index, 0, removedNode);
  } else {
    targetChildren.push(removedNode);
  }

  return removedNode;
}

function deleteNodeInMemory(data: PagesJson, nodeId: string): void {
  const location = findNodeById(data, nodeId);
  if (!location) {
    throw new PageEditorError(
      `Node with id "${nodeId}" not found in pages.json.`,
      'NODE_NOT_FOUND',
    );
  }

  if (location.slotMutator) {
    if (!location.slotMutator.remove) {
      throw new PageEditorError(
        `Node "${nodeId}" is a required singleton slot (e.g. list.itemRender or dialog action body) ` +
        'and cannot be deleted on its own. Delete the parent node instead.',
        'INVALID_PARENT',
      );
    }
    location.slotMutator.remove();
  } else {
    location.siblings.splice(location.index, 1);
  }
}

function addPageInMemory(
  data: PagesJson,
  pageData: { id: string; title: string; body?: unknown[] },
  index?: number,
): PageSummary {
  const { id, title, body = [] } = pageData;

  if (!PAGE_ID_PATTERN.test(id)) {
    throw new PageEditorError(
      `Invalid page id "${id}". Must match pattern [a-z0-9][a-z0-9-]* (lowercase alphanumeric and hyphens, start with letter or digit).`,
      'VALIDATION_ERROR',
    );
  }

  if (data.pages.some((p) => p.id === id)) {
    throw new PageEditorError(
      `Page with id "${id}" already exists in pages.json.`,
      'VALIDATION_ERROR',
    );
  }

  const newPage = { id, title, body };
  if (index !== undefined && index >= 0 && index <= data.pages.length) {
    (data.pages as unknown[]).splice(index, 0, newPage);
  } else {
    (data.pages as unknown[]).push(newPage);
  }
  return { id, title };
}

function removePageInMemory(data: PagesJson, pageId: string): void {
  const idx = data.pages.findIndex((p) => p.id === pageId);
  if (idx === -1) {
    throw new PageEditorError(
      `Page "${pageId}" not found in pages.json.`,
      'NODE_NOT_FOUND',
    );
  }
  data.pages.splice(idx, 1);
}

function updatePageMetaInMemory(
  data: PagesJson,
  pageId: string,
  props: { title?: string },
): PageSummary {
  if ('id' in props) {
    throw new PageEditorError(
      'Cannot modify page "id". Page ids are immutable.',
      'FORBIDDEN_UPDATE',
    );
  }

  const page = data.pages.find((p) => p.id === pageId);
  if (!page) {
    throw new PageEditorError(
      `Page "${pageId}" not found in pages.json.`,
      'NODE_NOT_FOUND',
    );
  }

  if (props.title !== undefined) {
    (page as Record<string, unknown>).title = props.title;
  }
  return { id: page.id, title: page.title };
}

// ============================================================
// Batch operation helpers
// ============================================================

const WRITE_BATCH_OPS: ReadonlySet<BatchOperation['op']> = new Set([
  'insert',
  'update',
  'delete',
  'move',
  'page_add',
  'page_remove',
  'page_update',
]);

function isWriteBatchOperation(operation: BatchOperation): boolean {
  return WRITE_BATCH_OPS.has(operation.op);
}

function buildBatchError(error: unknown): BatchError {
  if (error instanceof PageEditorError) {
    return {
      code: error.code,
      message: error.message,
      details: error.details,
    };
  }
  if (error instanceof Error) {
    return {
      code: 'UNKNOWN_ERROR',
      message: error.message,
    };
  }
  return {
    code: 'UNKNOWN_ERROR',
    message: String(error),
  };
}

function resolveRef(value: string, refMap: Map<string, string>): string {
  if (!value.startsWith('$')) return value;
  return refMap.get(value) ?? value;
}

function resolveRefOrThrow(value: string, refMap: Map<string, string>): string {
  const resolved = resolveRef(value, refMap);
  if (resolved.startsWith('$')) {
    throw new PageEditorError(
      `Reference "${value}" is not defined in current ui_batch context.`,
      'VALIDATION_ERROR',
    );
  }
  return resolved;
}

function getOperationDependencies(operation: BatchOperation): string[] {
  switch (operation.op) {
    case 'get':
    case 'update':
    case 'delete':
      return [
        operation.node_id,
        ...(operation.op === 'update'
          ? collectNestedRefTokens(operation.props).filter((token) => token !== '$self')
          : []),
      ];
    case 'insert':
      return [
        operation.parent_id,
        ...collectNestedRefTokens(operation.node).filter((token) => token !== '$self'),
      ];
    case 'move':
      return [operation.node_id, operation.new_parent_id];
    case 'page_remove':
    case 'page_update':
      return [operation.page_id];
    case 'page_add':
      return [];
    default:
      return [];
  }
}

function findFailedDependencyRef(
  operation: BatchOperation,
  failedRefs: Set<string>,
): string | undefined {
  const deps = getOperationDependencies(operation);
  for (const dep of deps) {
    if (dep.startsWith('$') && failedRefs.has(dep)) {
      return dep;
    }
  }
  return undefined;
}

function markRefFailed(
  refMap: Map<string, string>,
  failedRefs: Set<string>,
  ref?: string,
): void {
  if (!ref) return;
  refMap.delete(ref);
  failedRefs.add(ref);
}

function markRefResolved(
  refMap: Map<string, string>,
  failedRefs: Set<string>,
  ref: string | undefined,
  value: string,
): void {
  if (!ref) return;
  failedRefs.delete(ref);
  refMap.set(ref, value);
}

// ============================================================
// Public API
// ============================================================

/** Get an outline of the page structure (tree with IDs and summaries). */
export function getPageOutline(
  ctx: PageEditorContext,
  pageId?: string,
): PageOutlineResult {
  const data = readPagesJson(ctx);

  const pages = pageId
    ? data.pages.filter((p) => p.id === pageId)
    : data.pages;

  if (pageId && pages.length === 0) {
    throw new PageEditorError(
      `Page "${pageId}" not found in pages.json.`,
      'NODE_NOT_FOUND',
    );
  }

  return {
    pages: pages.map((page) => ({
      id: page.id,
      title: page.title,
      body: page.body.map(buildOutlineNode),
    })),
  };
}

/** Get full details of a component node by its stable ID. */
export function getNode(
  ctx: PageEditorContext,
  nodeId: string,
): ComponentSchema {
  const data = readPagesJson(ctx);
  return getNodeInMemory(data, nodeId);
}

/** Insert a new node as a child of the given parent node or page body. */
export function insertNode(
  ctx: PageEditorContext,
  parentId: string,
  nodeData: Record<string, unknown>,
  index?: number,
): ComponentSchema {
  const data = readPagesJson(ctx);
  const { nodeId } = insertNodeInMemory(data, parentId, nodeData, index);
  const saved = writePagesJson(ctx, data);
  const loc = findNodeById(saved, nodeId);
  return loc!.node;
}

/** Update properties of an existing node. Cannot change `id` or `type`. */
export function updateNode(
  ctx: PageEditorContext,
  nodeId: string,
  props: Record<string, unknown>,
): ComponentSchema {
  const data = readPagesJson(ctx);
  updateNodeInMemory(data, nodeId, props);
  const saved = writePagesJson(ctx, data);
  const loc = findNodeById(saved, nodeId);
  return loc!.node;
}

/** Move a node to a new parent at the given index. */
export function moveNode(
  ctx: PageEditorContext,
  nodeId: string,
  newParentId: string,
  index?: number,
): ComponentSchema {
  const data = readPagesJson(ctx);
  moveNodeInMemory(data, nodeId, newParentId, index);
  const saved = writePagesJson(ctx, data);
  const loc = findNodeById(saved, nodeId);
  return loc!.node;
}

/** Delete a node and its entire subtree. */
export function deleteNode(
  ctx: PageEditorContext,
  nodeId: string,
): void {
  const data = readPagesJson(ctx);
  deleteNodeInMemory(data, nodeId);
  writePagesJson(ctx, data);
}

/** List all pages with their id and title. */
export function listPages(ctx: PageEditorContext): PagesListResult {
  const data = readPagesJson(ctx);
  return {
    pages: data.pages.map((p) => ({ id: p.id, title: p.title })),
  };
}

/** Add a new page. The page id must be unique and match [a-z0-9][a-z0-9-]*. */
export function addPage(
  ctx: PageEditorContext,
  pageData: { id: string; title: string; body?: unknown[] },
  index?: number,
): PageSummary {
  const data = readPagesJson(ctx);
  const summary = addPageInMemory(data, pageData, index);
  writePagesJson(ctx, data);
  return summary;
}

/** Remove a page and all its components. */
export function removePage(ctx: PageEditorContext, pageId: string): void {
  const data = readPagesJson(ctx);
  removePageInMemory(data, pageId);
  writePagesJson(ctx, data);
}

/** Update page metadata (title only; id is immutable). */
export function updatePageMeta(
  ctx: PageEditorContext,
  pageId: string,
  props: { title?: string },
): PageSummary {
  const data = readPagesJson(ctx);
  const summary = updatePageMetaInMemory(data, pageId, props);
  writePagesJson(ctx, data);
  return summary;
}

/** Execute multiple operations in one pass with ref resolution and partial success. */
export function batchOperations(
  ctx: PageEditorContext,
  operations: BatchOperation[],
): BatchResult {
  const data = readPagesJson(ctx);
  const results: BatchOperationResult[] = [];
  const refMap = new Map<string, string>();
  const failedRefs = new Set<string>();
  let hasSuccessfulWrite = false;

  for (let index = 0; index < operations.length; index++) {
    const operation = operations[index];
    const baseResult = {
      index,
      op: operation.op,
      ref: operation.ref,
    } satisfies Pick<BatchOperationResult, 'index' | 'op' | 'ref'>;

    if (operation.ref && !operation.ref.startsWith('$')) {
      markRefFailed(refMap, failedRefs, operation.ref);
      results.push({
        ...baseResult,
        status: 'error',
        error: {
          code: 'VALIDATION_ERROR',
          message: `ref "${operation.ref}" must start with "$".`,
        },
      });
      continue;
    }

    const failedDependency = findFailedDependencyRef(operation, failedRefs);
    if (failedDependency) {
      markRefFailed(refMap, failedRefs, operation.ref);
      results.push({
        ...baseResult,
        status: 'skipped',
        skipped_reason: `Depends on failed reference "${failedDependency}".`,
      });
      continue;
    }

    try {
      switch (operation.op) {
        case 'get': {
          const nodeId = resolveRefOrThrow(operation.node_id, refMap);
          const node = getNodeInMemory(data, nodeId);
          markRefResolved(refMap, failedRefs, operation.ref, nodeId);
          results.push({
            ...baseResult,
            status: 'ok',
            node_id: nodeId,
            node,
          });
          break;
        }
        case 'insert': {
          const parentId = resolveRefOrThrow(operation.parent_id, refMap);
          const { node, nodeId } = insertNodeInMemory(
            data,
            parentId,
            operation.node,
            operation.index,
            refMap,
          );
          markRefResolved(refMap, failedRefs, operation.ref, nodeId);
          hasSuccessfulWrite = hasSuccessfulWrite || isWriteBatchOperation(operation);
          results.push({
            ...baseResult,
            status: 'ok',
            node_id: nodeId,
            node,
          });
          break;
        }
        case 'update': {
          const nodeId = resolveRefOrThrow(operation.node_id, refMap);
          const resolvedProps = resolveNestedRefs(operation.props, refMap, 'props');
          const node = updateNodeInMemory(data, nodeId, resolvedProps);
          markRefResolved(refMap, failedRefs, operation.ref, nodeId);
          hasSuccessfulWrite = hasSuccessfulWrite || isWriteBatchOperation(operation);
          results.push({
            ...baseResult,
            status: 'ok',
            node_id: nodeId,
            node,
          });
          break;
        }
        case 'delete': {
          const nodeId = resolveRefOrThrow(operation.node_id, refMap);
          deleteNodeInMemory(data, nodeId);
          markRefResolved(refMap, failedRefs, operation.ref, nodeId);
          hasSuccessfulWrite = hasSuccessfulWrite || isWriteBatchOperation(operation);
          results.push({
            ...baseResult,
            status: 'ok',
            node_id: nodeId,
            deleted: nodeId,
          });
          break;
        }
        case 'move': {
          const nodeId = resolveRefOrThrow(operation.node_id, refMap);
          const newParentId = resolveRefOrThrow(operation.new_parent_id, refMap);
          const node = moveNodeInMemory(data, nodeId, newParentId, operation.index);
          markRefResolved(refMap, failedRefs, operation.ref, nodeId);
          hasSuccessfulWrite = hasSuccessfulWrite || isWriteBatchOperation(operation);
          results.push({
            ...baseResult,
            status: 'ok',
            node_id: nodeId,
            node,
          });
          break;
        }
        case 'page_add': {
          const page = addPageInMemory(data, { id: operation.id, title: operation.title }, operation.index);
          markRefResolved(refMap, failedRefs, operation.ref, page.id);
          hasSuccessfulWrite = hasSuccessfulWrite || isWriteBatchOperation(operation);
          results.push({
            ...baseResult,
            status: 'ok',
            page_id: page.id,
            page,
          });
          break;
        }
        case 'page_remove': {
          const pageId = resolveRefOrThrow(operation.page_id, refMap);
          removePageInMemory(data, pageId);
          markRefResolved(refMap, failedRefs, operation.ref, pageId);
          hasSuccessfulWrite = hasSuccessfulWrite || isWriteBatchOperation(operation);
          results.push({
            ...baseResult,
            status: 'ok',
            page_id: pageId,
            deleted: pageId,
          });
          break;
        }
        case 'page_update': {
          const pageId = resolveRefOrThrow(operation.page_id, refMap);
          const page = updatePageMetaInMemory(data, pageId, { title: operation.title });
          markRefResolved(refMap, failedRefs, operation.ref, page.id);
          hasSuccessfulWrite = hasSuccessfulWrite || isWriteBatchOperation(operation);
          results.push({
            ...baseResult,
            status: 'ok',
            page_id: page.id,
            page,
          });
          break;
        }
        default: {
          const _exhaustive: never = operation;
          throw new Error(`Unhandled batch operation: ${JSON.stringify(_exhaustive)}`);
        }
      }
    } catch (error) {
      markRefFailed(refMap, failedRefs, operation.ref);
      results.push({
        ...baseResult,
        status: 'error',
        error: buildBatchError(error),
      });
    }
  }

  if (!hasSuccessfulWrite) {
    return {
      committed: false,
      results,
    };
  }

  try {
    writePagesJson(ctx, data);
    return {
      committed: true,
      results,
    };
  } catch (error) {
    return {
      committed: false,
      results,
      write_error: buildBatchError(error),
    };
  }
}

/** Move a page to a new index in the pages array. */
export function reorderPage(
  ctx: PageEditorContext,
  pageId: string,
  index: number,
): PagesListResult {
  const data = readPagesJson(ctx);
  const fromIdx = data.pages.findIndex((p) => p.id === pageId);

  if (fromIdx === -1) {
    throw new PageEditorError(
      `Page "${pageId}" not found in pages.json.`,
      'NODE_NOT_FOUND',
    );
  }

  if (index < 0 || index >= data.pages.length) {
    throw new PageEditorError(
      `Index ${index} is out of range. pages array has ${data.pages.length} items (valid range: 0–${data.pages.length - 1}).`,
      'VALIDATION_ERROR',
    );
  }

  const [page] = data.pages.splice(fromIdx, 1);
  data.pages.splice(index, 0, page);

  writePagesJson(ctx, data);
  return { pages: data.pages.map((p) => ({ id: p.id, title: p.title })) };
}
