/**
 * Page Editor — Core logic for structured editing of ui/pages.json
 *
 * Provides read and write operations for pages.json in the Agent working copy.
 * All write operations:
 *   1. Normalize (auto-assign missing IDs)
 *   2. Validate (Zod structure + semantic checks)
 *   3. Write back to working copy only if validation passes
 *
 * IDs are auto-generated by this module; callers must not specify IDs.
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

import {
  normalizePagesJson,
  validatePagesJson,
  generateNodeId,
  getComponentSummary,
  isContainerType,
} from '@cozybase/ui';
import type { PagesJson, ComponentSchema } from '@cozybase/ui';

const PAGES_JSON_PATH = 'ui/pages.json';

// ============================================================
// Types
// ============================================================

export interface PageEditorContext {
  appsDir: string;
  appName: string;
}

export interface OutlineNode {
  id: string;
  type: string;
  summary: string;
  children?: OutlineNode[];
}

export interface PageOutline {
  id: string;
  title: string;
  body: OutlineNode[];
}

export interface PageOutlineResult {
  pages: PageOutline[];
}

export class PageEditorError extends Error {
  constructor(
    message: string,
    public readonly code:
      | 'FILE_NOT_FOUND'
      | 'INVALID_JSON'
      | 'VALIDATION_ERROR'
      | 'NODE_NOT_FOUND'
      | 'INVALID_PARENT'
      | 'FORBIDDEN_UPDATE',
    public readonly details?: unknown,
  ) {
    super(message);
    this.name = 'PageEditorError';
  }
}

// ============================================================
// File I/O
// ============================================================

function getPagesJsonPath(ctx: PageEditorContext): string {
  return join(ctx.appsDir, ctx.appName, PAGES_JSON_PATH);
}

function readPagesJson(ctx: PageEditorContext): PagesJson {
  const filePath = getPagesJsonPath(ctx);
  if (!existsSync(filePath)) {
    throw new PageEditorError(
      `pages.json not found for app "${ctx.appName}". Run fetch_app first.`,
      'FILE_NOT_FOUND',
    );
  }

  let raw: unknown;
  let rawText: string;
  try {
    rawText = readFileSync(filePath, 'utf-8');
    raw = JSON.parse(rawText);
  } catch (e) {
    throw new PageEditorError(
      `Failed to parse pages.json: ${e instanceof Error ? e.message : String(e)}`,
      'INVALID_JSON',
    );
  }

  // Normalize (auto-assign IDs to any nodes missing them, mutates in place)
  normalizePagesJson(raw);

  // Validate after normalization
  const result = validatePagesJson(raw);
  if (!result.ok) {
    throw new PageEditorError(
      'pages.json has validation errors:\n' +
        result.errors.map((e) => `  ${e.path}: ${e.message}`).join('\n'),
      'VALIDATION_ERROR',
      result.errors,
    );
  }

  // Persist normalized IDs back to disk so repeated reads are stable.
  // Only write if normalization actually changed something.
  const normalizedText = JSON.stringify(result.data, null, 2);
  if (normalizedText !== rawText.trimEnd()) {
    writeFileSync(filePath, normalizedText, 'utf-8');
  }

  return result.data;
}

function writePagesJson(ctx: PageEditorContext, data: unknown): PagesJson {
  // Normalize before validating
  normalizePagesJson(data);

  // Validate
  const result = validatePagesJson(data);
  if (!result.ok) {
    throw new PageEditorError(
      'Validation failed — changes were not written:\n' +
        result.errors.map((e) => `  ${e.path}: ${e.message}`).join('\n'),
      'VALIDATION_ERROR',
      result.errors,
    );
  }

  // Write to working copy
  const filePath = getPagesJsonPath(ctx);
  writeFileSync(filePath, JSON.stringify(result.data, null, 2), 'utf-8');
  return result.data;
}

// ============================================================
// Shared component-slot walker
// ============================================================

/**
 * A visitor callback receives the child node, the mutable array it lives in,
 * its index within that array, and an optional SlotMutator for singleton slots.
 *
 * For normal array slots (children[], body[], etc.), `siblings` is the actual
 * array in the parent object, so `siblings[index] = x` and `siblings.splice()`
 * persist correctly.
 *
 * For singleton slots (itemRender, columns[].render, dialog-action body),
 * `slotMutator` is provided:
 *   - `slotMutator.set(node)` replaces the singleton in the parent object.
 *   - `slotMutator.remove()` deletes it (only defined for optional slots like
 *     columns[].render — required slots like list.itemRender and dialog body
 *     do not provide `remove`).
 *   Do NOT mutate `siblings[index]` for singleton slots.
 */
interface SlotMutator {
  set: (newNode: ComponentSchema) => void;
  remove?: () => void;
}

type SlotVisitor = (
  child: ComponentSchema,
  siblings: ComponentSchema[],
  index: number,
  slotMutator?: SlotMutator,
) => void;

/**
 * Visit every direct component child of `node` across ALL component-bearing
 * slots defined in the schema:
 *
 *   children[]        – row, col, card, dialog
 *   body[]            – card (alternate layout), tabs items, custom components
 *   items[i].body[]   – tabs panel bodies
 *   itemRender        – list (singleton)
 *   columns[i].render – table (singleton per column)
 *   action/onSuccess/onError body  – dialog-type actions (singleton)
 *
 * This is the single source of truth for traversal — normalize, validate,
 * find, subtree-check, and outline all delegate here so they stay in sync.
 */
function visitChildComponents(node: ComponentSchema, visitor: SlotVisitor): void {
  const n = node as Record<string, unknown>;

  // Standard array slots
  if (Array.isArray(n.children)) {
    const arr = n.children as ComponentSchema[];
    for (let i = 0; i < arr.length; i++) visitor(arr[i], arr, i);
  }

  if (Array.isArray(n.body)) {
    const arr = n.body as ComponentSchema[];
    for (let i = 0; i < arr.length; i++) visitor(arr[i], arr, i);
  }

  // tabs.items[].body
  if (Array.isArray(n.items)) {
    for (const tabItem of n.items as Array<Record<string, unknown>>) {
      if (Array.isArray(tabItem.body)) {
        const arr = tabItem.body as ComponentSchema[];
        for (let i = 0; i < arr.length; i++) visitor(arr[i], arr, i);
      }
    }
  }

  // list.itemRender (singleton, REQUIRED — no remove)
  if (n.itemRender && typeof n.itemRender === 'object' && !Array.isArray(n.itemRender)) {
    const wrapper = n.itemRender as ComponentSchema;
    visitor(wrapper, [wrapper], 0, {
      set: (newNode) => { n.itemRender = newNode; },
      // no remove: list.itemRender is required by schema
    });
  }

  // table.columns[].render (singleton per column, OPTIONAL — remove allowed)
  if (Array.isArray(n.columns)) {
    for (const col of n.columns as Array<Record<string, unknown>>) {
      if (col.render && typeof col.render === 'object') {
        const wrapper = col.render as ComponentSchema;
        visitor(wrapper, [wrapper], 0, {
          set: (newNode) => { col.render = newNode; },
          remove: () => { delete col.render; },
        });
      }
    }
  }

  // dialog-action bodies: action, onSuccess, onError (and nested confirm/cancel)
  visitActionComponentSlots(n.action, visitor);
  visitActionComponentSlots(n.onSuccess, visitor);
  visitActionComponentSlots(n.onError, visitor);

  if (Array.isArray(n.rowActions)) {
    for (const ra of n.rowActions as Array<Record<string, unknown>>) {
      visitActionComponentSlots(ra.action, visitor);
    }
  }
}

/** Recursively visit component-bearing slots inside action trees. */
function visitActionComponentSlots(actions: unknown, visitor: SlotVisitor): void {
  if (!actions) return;
  const list = Array.isArray(actions) ? actions : [actions];
  for (const action of list) {
    if (!action || typeof action !== 'object') continue;
    const a = action as Record<string, unknown>;
    if (a.type === 'dialog' && a.body && typeof a.body === 'object') {
      const wrapper = a.body as ComponentSchema;
      visitor(wrapper, [wrapper], 0, {
        set: (newNode) => { a.body = newNode; },
        // no remove: dialog action body is required by schema
      });
    }
    // Recurse into nested action chains
    visitActionComponentSlots(a.onSuccess, visitor);
    visitActionComponentSlots(a.onError, visitor);
    visitActionComponentSlots(a.onConfirm, visitor);
    visitActionComponentSlots(a.onCancel, visitor);
  }
}

// ============================================================
// Node traversal utilities
// ============================================================

interface NodeLocation {
  node: ComponentSchema;
  /** The array this node lives in */
  siblings: ComponentSchema[];
  /** Index within siblings */
  index: number;
  /**
   * For singleton slots, provides set/remove operations that persist to the
   * parent object. Undefined for normal array slots where direct array
   * mutation (`siblings[index] =`, `siblings.splice()`) works correctly.
   */
  slotMutator?: SlotMutator;
}

function findNodeById(
  data: PagesJson,
  nodeId: string,
): NodeLocation | null {
  for (const page of data.pages) {
    const found = findInArray(page.body, nodeId);
    if (found) return found;
  }
  return null;
}

function findInArray(
  arr: ComponentSchema[],
  nodeId: string,
): NodeLocation | null {
  for (let i = 0; i < arr.length; i++) {
    const node = arr[i];
    if ((node as { id: string }).id === nodeId) {
      return { node, siblings: arr, index: i };
    }
    const found = findInChildSlots(node, nodeId);
    if (found) return found;
  }
  return null;
}

function findInChildSlots(
  node: ComponentSchema,
  nodeId: string,
): NodeLocation | null {
  let result: NodeLocation | null = null;
  visitChildComponents(node, (child, siblings, index, slotMutator) => {
    if (result) return; // already found
    if ((child as { id: string }).id === nodeId) {
      result = { node: child, siblings, index, slotMutator };
      return;
    }
    const deeper = findInChildSlots(child, nodeId);
    if (deeper) result = deeper;
  });
  return result;
}

/**
 * Returns true if `targetId` appears anywhere in the subtree rooted at `node`
 * (including `node` itself). Used to prevent moving a node into its own subtree.
 */
function isAncestorOf(
  nodeToMove: ComponentSchema,
  targetId: string,
): boolean {
  if ((nodeToMove as { id: string }).id === targetId) return true;
  return subtreeContainsId(nodeToMove, targetId);
}

function subtreeContainsId(node: ComponentSchema, id: string): boolean {
  let found = false;
  visitChildComponents(node, (child) => {
    if (found) return;
    if ((child as { id: string }).id === id) {
      found = true;
      return;
    }
    if (subtreeContainsId(child, id)) found = true;
  });
  return found;
}

/** Get the mutable children array of a container node, if applicable. */
function getChildrenArray(node: ComponentSchema): ComponentSchema[] | null {
  const n = node as Record<string, unknown>;
  if (Array.isArray(n.children)) return n.children as ComponentSchema[];
  if (Array.isArray(n.body)) return n.body as ComponentSchema[];
  return null;
}

// ============================================================
// Outline generation
// ============================================================

function buildOutlineNode(node: ComponentSchema): OutlineNode {
  const n = node as Record<string, unknown>;
  const id = String(n.id ?? '');
  const type = String(n.type ?? '');
  const summary = getComponentSummary(n);

  // Collect all child outline nodes via the shared walker
  const childOutlines: OutlineNode[] = [];
  visitChildComponents(node, (child) => {
    childOutlines.push(buildOutlineNode(child));
  });

  if (childOutlines.length > 0) {
    return { id, type, summary, children: childOutlines };
  }
  return { id, type, summary };
}

// ============================================================
// Public API
// ============================================================

/** Get an outline of the page structure (tree with IDs and summaries). */
export function getPageOutline(
  ctx: PageEditorContext,
  pageId?: string,
): PageOutlineResult {
  const data = readPagesJson(ctx);

  const pages = pageId
    ? data.pages.filter((p) => p.id === pageId)
    : data.pages;

  if (pageId && pages.length === 0) {
    throw new PageEditorError(
      `Page "${pageId}" not found in pages.json.`,
      'NODE_NOT_FOUND',
    );
  }

  return {
    pages: pages.map((page) => ({
      id: page.id,
      title: page.title,
      body: page.body.map(buildOutlineNode),
    })),
  };
}

/** Get full details of a component node by its stable ID. */
export function getNode(
  ctx: PageEditorContext,
  nodeId: string,
): ComponentSchema {
  const data = readPagesJson(ctx);
  const location = findNodeById(data, nodeId);

  if (!location) {
    throw new PageEditorError(
      `Node with id "${nodeId}" not found in pages.json.`,
      'NODE_NOT_FOUND',
    );
  }

  return location.node;
}

/** Insert a new node as a child of the given parent node or page body. */
export function insertNode(
  ctx: PageEditorContext,
  parentId: string,
  nodeData: Record<string, unknown>,
  index?: number,
): ComponentSchema {
  const data = readPagesJson(ctx);

  // Auto-generate ID — remove any id the caller may have specified
  const nodeType = String(nodeData.type ?? 'unknown');
  const newNode = {
    ...nodeData,
    id: generateNodeId(nodeType),
  };

  // Check if parentId refers to a page (top-level body insertion)
  const page = data.pages.find((p) => p.id === parentId);
  if (page) {
    const body = page.body as ComponentSchema[];
    if (index !== undefined && index >= 0 && index <= body.length) {
      body.splice(index, 0, newNode as ComponentSchema);
    } else {
      body.push(newNode as ComponentSchema);
    }
    const saved = writePagesJson(ctx, data);
    const loc = findNodeById(saved, newNode.id as string);
    return loc!.node;
  }

  // Find parent component node
  const parentLocation = findNodeById(data, parentId);
  if (!parentLocation) {
    throw new PageEditorError(
      `Parent "${parentId}" not found in pages.json. Use a page id or a container node id.`,
      'INVALID_PARENT',
    );
  }

  const parentNode = parentLocation.node;

  // Check parent is a container type
  const parentType = (parentNode as { type: string }).type;
  if (!isContainerType(parentType)) {
    throw new PageEditorError(
      `Node "${parentId}" (type: "${parentType}") cannot contain children. Only container types can have children.`,
      'INVALID_PARENT',
    );
  }

  const children = getChildrenArray(parentNode);
  if (!children) {
    throw new PageEditorError(
      `Node "${parentId}" has no children array.`,
      'INVALID_PARENT',
    );
  }

  // Insert at position
  if (index !== undefined && index >= 0 && index <= children.length) {
    children.splice(index, 0, newNode as ComponentSchema);
  } else {
    children.push(newNode as ComponentSchema);
  }

  // Write back (validates before writing)
  const saved = writePagesJson(ctx, data);

  // Find and return the newly inserted node
  const loc = findNodeById(saved, newNode.id as string);
  return loc!.node;
}

/** Update properties of an existing node. Cannot change `id` or `type`. */
export function updateNode(
  ctx: PageEditorContext,
  nodeId: string,
  props: Record<string, unknown>,
): ComponentSchema {
  // Forbid changing id or type
  if ('id' in props) {
    throw new PageEditorError(
      'Cannot modify "id" via page_update. Node IDs are stable and managed by the system.',
      'FORBIDDEN_UPDATE',
    );
  }
  if ('type' in props) {
    throw new PageEditorError(
      'Cannot modify "type" via page_update. To change a node\'s type, use page_delete then page_insert.',
      'FORBIDDEN_UPDATE',
    );
  }

  const data = readPagesJson(ctx);
  const location = findNodeById(data, nodeId);

  if (!location) {
    throw new PageEditorError(
      `Node with id "${nodeId}" not found in pages.json.`,
      'NODE_NOT_FOUND',
    );
  }

  // Merge props into the node
  const updated = { ...(location.node as Record<string, unknown>), ...props } as ComponentSchema;
  if (location.slotMutator) {
    location.slotMutator.set(updated);
  } else {
    location.siblings[location.index] = updated;
  }

  const saved = writePagesJson(ctx, data);
  const loc = findNodeById(saved, nodeId);
  return loc!.node;
}

/** Move a node to a new parent at the given index. */
export function moveNode(
  ctx: PageEditorContext,
  nodeId: string,
  newParentId: string,
  index?: number,
): ComponentSchema {
  const data = readPagesJson(ctx);

  // Locate the node to move
  const nodeLocation = findNodeById(data, nodeId);
  if (!nodeLocation) {
    throw new PageEditorError(
      `Node with id "${nodeId}" not found in pages.json.`,
      'NODE_NOT_FOUND',
    );
  }

  // Guard: moving a node into its own subtree would corrupt the tree
  if (isAncestorOf(nodeLocation.node, newParentId)) {
    throw new PageEditorError(
      `Cannot move node "${nodeId}" into its own descendant "${newParentId}".`,
      'INVALID_PARENT',
    );
  }

  // Locate the new parent
  const parentLocation = findNodeById(data, newParentId);
  if (!parentLocation) {
    throw new PageEditorError(
      `Parent node "${newParentId}" not found in pages.json.`,
      'INVALID_PARENT',
    );
  }

  const parentType = (parentLocation.node as { type: string }).type;
  if (!isContainerType(parentType)) {
    throw new PageEditorError(
      `Node "${newParentId}" (type: "${parentType}") cannot contain children.`,
      'INVALID_PARENT',
    );
  }

  const targetChildren = getChildrenArray(parentLocation.node);
  if (!targetChildren) {
    throw new PageEditorError(
      `Parent node "${newParentId}" has no children array.`,
      'INVALID_PARENT',
    );
  }

  // Remove from current location
  let removedNode: ComponentSchema;
  if (nodeLocation.slotMutator) {
    if (!nodeLocation.slotMutator.remove) {
      throw new PageEditorError(
        `Node "${nodeId}" is a required singleton slot (e.g. list.itemRender or dialog action body) ` +
        `and cannot be moved out of its parent. Delete the parent node and re-insert instead.`,
        'INVALID_PARENT',
      );
    }
    removedNode = nodeLocation.node;
    nodeLocation.slotMutator.remove();
  } else {
    [removedNode] = nodeLocation.siblings.splice(nodeLocation.index, 1);
  }

  // Insert into new location
  if (index !== undefined && index >= 0 && index <= targetChildren.length) {
    targetChildren.splice(index, 0, removedNode);
  } else {
    targetChildren.push(removedNode);
  }

  const saved = writePagesJson(ctx, data);
  const loc = findNodeById(saved, nodeId);
  return loc!.node;
}

/** Delete a node and its entire subtree. */
export function deleteNode(
  ctx: PageEditorContext,
  nodeId: string,
): void {
  const data = readPagesJson(ctx);
  const location = findNodeById(data, nodeId);

  if (!location) {
    throw new PageEditorError(
      `Node with id "${nodeId}" not found in pages.json.`,
      'NODE_NOT_FOUND',
    );
  }

  if (location.slotMutator) {
    if (!location.slotMutator.remove) {
      throw new PageEditorError(
        `Node "${nodeId}" is a required singleton slot (e.g. list.itemRender or dialog action body) ` +
        `and cannot be deleted on its own. Delete the parent node instead.`,
        'INVALID_PARENT',
      );
    }
    location.slotMutator.remove();
  } else {
    location.siblings.splice(location.index, 1);
  }
  writePagesJson(ctx, data);
}
