import { afterEach, describe, expect, test } from 'bun:test';
import type { AgentEvent, AgentProvider, AgentQuery, AgentQueryConfig } from '@cozybase/agent';
import { ChatSession } from '../../src/agent/chat-session';
import { SessionStore } from '../../src/agent/session-store';
import { createTestApp, createTestWorkspace, type TestWorkspaceHandle } from '../helpers/test-workspace';

class StubAgentQuery implements AgentQuery {
  constructor(
    private readonly events: AgentEvent[],
    private readonly interruptFn: () => Promise<void> = async () => {},
  ) {}

  async interrupt(): Promise<void> {
    await this.interruptFn();
  }

  close(): void {}

  async *[Symbol.asyncIterator](): AsyncGenerator<AgentEvent> {
    for (const event of this.events) {
      yield event;
    }
  }
}

class StubAgentProvider implements AgentProvider {
  public lastConfig: AgentQueryConfig | null = null;

  constructor(private readonly queryFactory: () => AgentQuery) {}

  createQuery(config: AgentQueryConfig): AgentQuery {
    this.lastConfig = config;
    return this.queryFactory();
  }

  async isAvailable(): Promise<boolean> {
    return true;
  }

  dispose(): void {}
}

class FakeWebSocket {
  readyState = 1;
  messages: unknown[] = [];

  send(data: string): void {
    this.messages.push(JSON.parse(data));
  }
}

describe('ChatSession', () => {
  let handle: TestWorkspaceHandle;

  afterEach(() => {
    handle?.cleanup();
  });

  test('keeps the persisted session id when a run completes with an empty sessionId', async () => {
    handle = createTestWorkspace();
    createTestApp(handle, 'orders');
    const store = new SessionStore(handle.workspace.getPlatformDb());
    store.saveSessionId('orders', 'sess-existing');

    const provider = new StubAgentProvider(() => new StubAgentQuery([
      { type: 'conversation.run.started' },
      { type: 'conversation.run.completed', sessionId: '' },
    ]));

    const session = new ChatSession(
      'orders',
      {
        agentProvider: provider,
        providerKind: 'claude',
        agentDir: handle.root,
      },
      store,
      'sess-existing',
    );
    const ws = new FakeWebSocket();
    session.connect(ws);

    await session.handleMessage(ws, JSON.stringify({ type: 'chat:send', message: 'hello' }));

    expect(store.getSessionId('orders')).toBe('sess-existing');
    expect(provider.lastConfig?.resumeSessionId).toBe('sess-existing');
    expect(ws.messages).toContainEqual({ type: 'conversation.run.completed', sessionId: '' });
  });

  test('restores tool history in started-time order even when completion arrives later', async () => {
    handle = createTestWorkspace();
    createTestApp(handle, 'orders');
    const store = new SessionStore(handle.workspace.getPlatformDb());

    const provider = new StubAgentProvider(() => new StubAgentQuery([
      { type: 'conversation.run.started' },
      { type: 'conversation.tool.started', toolUseId: 'tool-1', toolName: 'Read' },
      { type: 'conversation.message.started', messageId: 'm-1', role: 'assistant' },
      { type: 'conversation.message.completed', messageId: 'm-1', role: 'assistant', content: 'done' },
      { type: 'conversation.tool.completed', toolUseId: 'tool-1', toolName: 'Read', summary: 'read files' },
      { type: 'conversation.run.completed', sessionId: 'sess-1' },
    ]));

    const session = new ChatSession(
      'orders',
      {
        agentProvider: provider,
        providerKind: 'claude',
        agentDir: handle.root,
      },
      store,
    );
    const ws = new FakeWebSocket();
    session.connect(ws);

    await session.handleMessage(ws, JSON.stringify({ type: 'chat:send', message: 'hello' }));

    const history = store.getMessages('orders');
    expect(history).toEqual([
      expect.objectContaining({ role: 'user', content: 'hello' }),
      expect.objectContaining({
        role: 'tool',
        content: '',
        toolName: 'Read',
        toolStatus: 'done',
        toolSummary: 'read files',
      }),
      expect.objectContaining({ role: 'assistant', content: 'done' }),
    ]);
  });

  test('passes provider options generated by providerOptionsFactory', async () => {
    handle = createTestWorkspace();
    createTestApp(handle, 'orders');
    const store = new SessionStore(handle.workspace.getPlatformDb());

    const provider = new StubAgentProvider(() => new StubAgentQuery([
      { type: 'conversation.run.started' },
      { type: 'conversation.run.completed', sessionId: 'sess-1' },
    ]));

    const session = new ChatSession(
      'orders',
      {
        agentProvider: provider,
        providerKind: 'claude',
        agentDir: handle.root,
        providerOptionsFactory: ({ appSlug, mode }) => ({
          marker: `${appSlug}:${mode}`,
        }),
      },
      store,
    );
    const ws = new FakeWebSocket();
    session.connect(ws);

    await session.handleMessage(ws, JSON.stringify({ type: 'chat:send', message: 'hello' }));

    expect(provider.lastConfig?.providerOptions).toEqual({ marker: 'orders:chat' });
  });

  test('uses the latest runtime resolver values for provider, model, and resume clearing', async () => {
    handle = createTestWorkspace();
    createTestApp(handle, 'orders');
    const store = new SessionStore(handle.workspace.getPlatformDb());
    store.saveSessionId('orders', 'sess-claude', 'claude');

    const claudeProvider = new StubAgentProvider(() => new StubAgentQuery([
      { type: 'conversation.run.started' },
      { type: 'conversation.run.completed', sessionId: 'sess-claude-next' },
    ]));
    const codexProvider = new StubAgentProvider(() => new StubAgentQuery([
      { type: 'conversation.run.started' },
      { type: 'conversation.run.completed', sessionId: 'thread-codex-1' },
    ]));

    let providerKind: 'claude' | 'codex' = 'codex';

    const session = new ChatSession(
      'orders',
      {
        agentProvider: claudeProvider,
        providerKind: 'claude',
        agentDir: handle.root,
        runtimeResolver: () => (
          providerKind === 'claude'
            ? {
                agentProvider: claudeProvider,
                providerKind: 'claude',
                model: 'claude-opus-4-6',
              }
            : {
                agentProvider: codexProvider,
                providerKind: 'codex',
                model: 'gpt-5.4',
              }
        ),
      },
      store,
      'sess-claude',
    );
    const ws = new FakeWebSocket();
    session.connect(ws);

    await session.handleMessage(ws, JSON.stringify({ type: 'chat:send', message: 'hello' }));

    expect(claudeProvider.lastConfig).toBeNull();
    expect(codexProvider.lastConfig?.model).toBe('gpt-5.4');
    expect(codexProvider.lastConfig?.resumeSessionId).toBeNull();
    expect(store.getSession('orders')).toEqual({
      sdkSessionId: 'thread-codex-1',
      providerKind: 'codex',
    });
  });
});
