import { Database } from 'bun:sqlite';
import { mkdirSync, existsSync, readdirSync, readFileSync } from 'fs';
import { dirname } from 'path';
import { HTTP_METHODS, type HttpMethod } from './modules/functions/types';

export type AppMode = 'stable' | 'draft';
export type AppStatus = 'running' | 'stopped';

export interface AppEntry {
  name: string;
  mode: AppMode;
  status: AppStatus;
  dbPath: string;
  functionsDir: string;
  uiDir: string;

  // Runtime resources
  db: Database | null;
  moduleCache: Map<string, any>;
}

export interface AppStartRequest {
  mode: AppMode;
  dbPath: string;
  functionsDir: string;
  uiDir: string;
}

export interface FunctionDefinition {
  name: string;
  methods: HttpMethod[];
}

function registryKey(name: string, mode: AppMode): string {
  return `${name}:${mode}`;
}

export class AppRegistry {
  private apps = new Map<string, AppEntry>();
  private _themeCSS = '';

  /** Set the theme CSS string (generated by @cozybase/ui) */
  setThemeCSS(css: string): void {
    this._themeCSS = css;
  }

  /** Get the current theme CSS string */
  getThemeCSS(): string {
    return this._themeCSS;
  }

  /** Get an app entry by name and mode */
  get(name: string, mode: AppMode): AppEntry | undefined {
    return this.apps.get(registryKey(name, mode));
  }

  /** Get all app entries */
  getAll(): AppEntry[] {
    return Array.from(this.apps.values());
  }

  getFunctionDefinitions(name: string, mode: AppMode): FunctionDefinition[] {
    const entry = this.get(name, mode);
    if (!entry || !existsSync(entry.functionsDir)) {
      return [];
    }

    return readdirSync(entry.functionsDir)
      .filter((fileName) => fileName.endsWith('.ts'))
      .map((fileName) => {
        const functionName = fileName.replace(/\.ts$/, '');
        const source = readFileSync(`${entry.functionsDir}/${fileName}`, 'utf-8');
        return {
          name: functionName,
          methods: detectFunctionMethods(source),
        };
      })
      .filter((definition) => !definition.name.startsWith('_'))
      .sort((a, b) => a.name.localeCompare(b.name));
  }

  /** Start an app — open DB, init module cache, set status to running */
  start(name: string, config: AppStartRequest): AppEntry {
    const key = registryKey(name, config.mode);
    const existing = this.apps.get(key);

    if (existing && existing.status === 'running') {
      throw new AppRegistryError(409, `App '${name}:${config.mode}' is already running`);
    }

    // Open DB connection
    mkdirSync(dirname(config.dbPath), { recursive: true });
    const db = new Database(config.dbPath);
    db.exec('PRAGMA journal_mode = WAL');
    db.exec('PRAGMA foreign_keys = ON');

    const entry: AppEntry = {
      name,
      mode: config.mode,
      status: 'running',
      dbPath: config.dbPath,
      functionsDir: config.functionsDir,
      uiDir: config.uiDir,
      db,
      moduleCache: new Map(),
    };

    this.apps.set(key, entry);
    return entry;
  }

  /** Stop an app — close DB, clear module cache, set status to stopped */
  stop(name: string, mode: AppMode): void {
    const key = registryKey(name, mode);
    const entry = this.apps.get(key);

    if (!entry) {
      throw new AppRegistryError(404, `App '${name}:${mode}' not found`);
    }

    this.releaseResources(entry);
    entry.status = 'stopped';
  }

  /** Restart an app — stop (release resources) then start with new config */
  restart(name: string, config: AppStartRequest): AppEntry {
    const key = registryKey(name, config.mode);
    const existing = this.apps.get(key);

    // If exists, release old resources
    if (existing) {
      this.releaseResources(existing);
      this.apps.delete(key);
    }

    // Start with new config
    return this.start(name, config);
  }

  /** Shutdown all apps — stop everything */
  shutdownAll(): void {
    for (const entry of this.apps.values()) {
      if (entry.status === 'running') {
        this.releaseResources(entry);
        entry.status = 'stopped';
      }
    }
    this.apps.clear();
  }

  private releaseResources(entry: AppEntry): void {
    if (entry.db) {
      try {
        entry.db.close();
      } catch {
        // ignore close errors
      }
      entry.db = null;
    }
    entry.moduleCache.clear();
  }
}

function detectFunctionMethods(source: string): HttpMethod[] {
  const methods = HTTP_METHODS.filter((method) => (
    new RegExp(`export\\s+(?:async\\s+)?function\\s+${method}\\b|export\\s+const\\s+${method}\\b`).test(source)
  ));

  if (methods.length > 0) {
    return methods;
  }

  if (/export\s+default\b/.test(source)) {
    return [...HTTP_METHODS];
  }

  return ['GET'];
}

export class AppRegistryError extends Error {
  constructor(
    public statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = 'AppRegistryError';
  }
}
